

name: MathUtility using Maven, CI (GitHub ) | © 2023 giáo.làng

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8.0 - Mượn JDK của server 
      uses: actions/setup-java@v3
      with:
        java-version: '8.0'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven - đóng gói app thành .Jar bên Server Mỹ
      run: mvn -B package --file pom.xml

    - name: Distribute jar-war file # Gửi file .jar .war đi đâu, CD nhảy vào ...
      run: mkdir staging && cp target/*.jar staging # tạo thư mục staging chứa file .jar .war sau khi build      
     
    - name: Make hyperlink to jar-war file # Tạo hyperlink để download build 
      uses: actions/upload-artifact@v1
      with:
        name: math-util-mvn.zip # Bản build được nén thành math-util-mvn.zip để tải 
        path: staging
